version: '3.0'
services:
  chatbot:
    image: comp7940group.azurecr.io/chatbot:v2.3
    volumes:
      - ./chatbot.py:/chatbot.py
    environment:
      - REDIS_HOST=redis
      - REDIS_PASSWORD=comp7940project
      - REDIS_PORT=6379
      - OPENAI_API_KEY=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
    entrypoint: python chatbot.py
    depends_on:
      - redis
  redis:
    image: comp7940group.azurecr.io/redis:v1
    command: redis-server /usr/local/etc/redis/redis.conf